// <auto-generated />
using System;
using CoreBanking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreBanking.Infrastructure.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    partial class BankingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreBanking.Core.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AccountNumber");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOpened")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde"),
                            AccountNumber = "1000000001",
                            AccountStatus = 0,
                            AccountType = "Checking",
                            CustomerId = new Guid("a1b2c3d4-1234-5678-9abc-123456789abc"),
                            DateCreated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOpened = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RowVersion = new byte[] { 1, 0, 0, 0 }
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-4567-8901-def2-456789012def"),
                            AccountNumber = "1000000002",
                            AccountStatus = 0,
                            AccountType = "Savings",
                            CustomerId = new Guid("b2c3d4e5-2345-6789-abcd-234567890bcd"),
                            DateCreated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOpened = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            RowVersion = new byte[] { 1, 0, 0, 1 }
                        });
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BVN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1234-5678-9abc-123456789abc"),
                            BVN = "20000000009",
                            CreditScore = 40,
                            DateCreated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1995, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alice",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2345-6789-abcd-234567890bcd"),
                            BVN = "20000000010",
                            CreditScore = 55,
                            DateCreated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1988, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Bob",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Smith"
                        });
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("RelatedAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelatedAccountId");

                    b.Property<decimal>("RunningBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RelatedAccountId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("FromAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("InitiatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ToAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromAccountId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("Status");

                    b.HasIndex("ToAccountId");

                    b.ToTable("Transfers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6a7b8-5678-9012-0001-567890123001"),
                            CompletedAt = new DateTime(2024, 10, 1, 10, 30, 5, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2024, 10, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 1, 10, 30, 5, 0, DateTimeKind.Utc),
                            Description = "Payment for services",
                            FromAccountId = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde"),
                            InitiatedAt = new DateTime(2024, 10, 1, 10, 30, 0, 0, DateTimeKind.Utc),
                            Reference = "TRF-20241001-001",
                            Status = "Completed",
                            ToAccountId = new Guid("d4e5f6a7-4567-8901-def2-456789012def")
                        },
                        new
                        {
                            Id = new Guid("f6a7b8c9-6789-0123-0002-678901234002"),
                            DateCreated = new DateTime(2024, 11, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 11, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scheduled monthly payment",
                            FromAccountId = new Guid("d4e5f6a7-4567-8901-def2-456789012def"),
                            InitiatedAt = new DateTime(2024, 11, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Reference = "TRF-20241110-002",
                            ScheduledAt = new DateTime(2024, 11, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            ToAccountId = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde")
                        },
                        new
                        {
                            Id = new Guid("a7b8c9d0-7890-1234-0003-789012345003"),
                            CompletedAt = new DateTime(2024, 10, 5, 14, 20, 3, 0, DateTimeKind.Utc),
                            DateCreated = new DateTime(2024, 10, 5, 14, 20, 0, 0, DateTimeKind.Utc),
                            DateUpdated = new DateTime(2024, 10, 5, 14, 20, 3, 0, DateTimeKind.Utc),
                            Description = "Purchase payment - Failed: Insufficient funds",
                            FromAccountId = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde"),
                            InitiatedAt = new DateTime(2024, 10, 5, 14, 20, 0, 0, DateTimeKind.Utc),
                            Reference = "TRF-20241005-003",
                            Status = "Failed",
                            ToAccountId = new Guid("d4e5f6a7-4567-8901-def2-456789012def")
                        });
                });

            modelBuilder.Entity("CoreBanking.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Account", b =>
                {
                    b.HasOne("CoreBanking.Core.Entities.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoreBanking.Core.ValueObjects.Money", "AvailableBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("AvailableBalance_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("NGN")
                                .HasColumnName("AvailableBalance_Currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");

                            b1.HasData(
                                new
                                {
                                    AccountId = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde"),
                                    Amount = 1500.00m,
                                    Currency = "NGN"
                                },
                                new
                                {
                                    AccountId = new Guid("d4e5f6a7-4567-8901-def2-456789012def"),
                                    Amount = 5000.00m,
                                    Currency = "NGN"
                                });
                        });

                    b.OwnsOne("CoreBanking.Core.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentBalance_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasDefaultValue("NGN")
                                .HasColumnName("CurrentBalance_Currency");

                            b1.HasKey("AccountId");

                            b1.ToTable("Accounts");

                            b1.WithOwner()
                                .HasForeignKey("AccountId");

                            b1.HasData(
                                new
                                {
                                    AccountId = new Guid("c3d4e5f6-3456-7890-cde1-345678901cde"),
                                    Amount = 1500.00m,
                                    Currency = "NGN"
                                },
                                new
                                {
                                    AccountId = new Guid("d4e5f6a7-4567-8901-def2-456789012def"),
                                    Amount = 5000.00m,
                                    Currency = "NGN"
                                });
                        });

                    b.Navigation("AvailableBalance")
                        .IsRequired();

                    b.Navigation("CurrentBalance")
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Customer", b =>
                {
                    b.OwnsOne("CoreBanking.Core.ValueObjects.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("Email");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("CoreBanking.Core.ValueObjects.Address", "Address", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoCustomerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Address_City");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Address_Country");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)")
                                        .HasColumnName("Address_State");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)")
                                        .HasColumnName("Address_Street");

                                    b2.Property<string>("ZipCode")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)")
                                        .HasColumnName("Address_ZipCode");

                                    b2.HasKey("ContactInfoCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoCustomerId");

                                    b2.HasData(
                                        new
                                        {
                                            ContactInfoCustomerId = new Guid("a1b2c3d4-1234-5678-9abc-123456789abc"),
                                            City = "Lagos",
                                            Country = "Nigeria",
                                            State = "Lagos",
                                            Street = "123 Main St",
                                            ZipCode = "100001"
                                        },
                                        new
                                        {
                                            ContactInfoCustomerId = new Guid("b2c3d4e5-2345-6789-abcd-234567890bcd"),
                                            City = "Lagos",
                                            Country = "Nigeria",
                                            State = "Lagos",
                                            Street = "456 Victoria Island",
                                            ZipCode = "101001"
                                        });
                                });

                            b1.Navigation("Address")
                                .IsRequired();

                            b1.HasData(
                                new
                                {
                                    CustomerId = new Guid("a1b2c3d4-1234-5678-9abc-123456789abc"),
                                    Email = "alice.johnson@email.com",
                                    PhoneNumber = "555-0101"
                                },
                                new
                                {
                                    CustomerId = new Guid("b2c3d4e5-2345-6789-abcd-234567890bcd"),
                                    Email = "bob.smith@email.com",
                                    PhoneNumber = "555-0202"
                                });
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Transaction", b =>
                {
                    b.HasOne("CoreBanking.Core.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreBanking.Core.Entities.Account", "RelatedAccount")
                        .WithMany()
                        .HasForeignKey("RelatedAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("CoreBanking.Core.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Transaction_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Transaction_Currency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions");

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("RelatedAccount");
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Transfer", b =>
                {
                    b.HasOne("CoreBanking.Core.Entities.Account", "FromAccount")
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreBanking.Core.Entities.Account", "ToAccount")
                        .WithMany()
                        .HasForeignKey("ToAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CoreBanking.Core.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("TransferId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Transfer_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Transfer_Currency");

                            b1.HasKey("TransferId");

                            b1.ToTable("Transfers");

                            b1.WithOwner()
                                .HasForeignKey("TransferId");

                            b1.HasData(
                                new
                                {
                                    TransferId = new Guid("e5f6a7b8-5678-9012-0001-567890123001"),
                                    Amount = 500.00m,
                                    Currency = "NGN"
                                },
                                new
                                {
                                    TransferId = new Guid("f6a7b8c9-6789-0123-0002-678901234002"),
                                    Amount = 1000.00m,
                                    Currency = "NGN"
                                },
                                new
                                {
                                    TransferId = new Guid("a7b8c9d0-7890-1234-0003-789012345003"),
                                    Amount = 2500.00m,
                                    Currency = "NGN"
                                });
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("FromAccount");

                    b.Navigation("ToAccount");
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CoreBanking.Core.Entities.Customer", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
